create or replace PACKAGE BODY REPORTDATAGENERATOR AS

/*------------------------------------------------------------------------------*/
/* NOMBRE    : GETREPORTDATA                                                    */
/* OBJETIVO  : GENERAR DATOS PARA REPORTES DEL MÓDULO ADMINISTRACIÓN            */
/* PARAMETROS: 1 - SCODE        : CODIGO DE IDENTIFICACION DEL REPORTE 		    */
/*             2 - NTYPEREPORT  : TIPO DE REPORTE A GENERAR                     */
/*             3 - DSTARTDATE   : FECHA INICIAL DEL PERIODO A CONSULTAR         */
/*             4 - DENDDATE     : FECHA FINAL DEL PERIODO A CONSULTAR           */
/*             5 - NAFILIADOID  : ID DEL AFILIADO (SI APLICA)                   */
/*             6 - REPORTCURSOR : CURSOR DE SALIDA CON LOS DATOS DEL REPORTE    */
/*                                                                              */
/*------------------------------------------------------------------------------*/
PROCEDURE CREATERETRIEVEREPORTDATA (
    SCODE           IN  REPORTES.CODIGOIDENTIFICATORIO%TYPE DEFAULT NULL,
    NTYPEREPORT     IN  REPORTES.TIPO%TYPE DEFAULT NULL,
    DSTARTDATE      IN  REPORTES.FECHADESDE%TYPE DEFAULT NULL,
    DENDDATE        IN  REPORTES.FECHAHASTA%TYPE DEFAULT NULL,
    NAFILIADOID     IN  REPORTES.AFILIADOID%TYPE DEFAULT NULL,
    HEXAID          OUT REPORTES.CODIGOIDENTIFICATORIO%TYPE,
    REPORTCURSOR    OUT SYS_REFCURSOR
) IS
V_SCODE         REPORTES.CODIGOIDENTIFICATORIO%TYPE := SCODE;
V_NTYPEREPORT   REPORTES.TIPO%TYPE                  := NTYPEREPORT;
V_DSTARTDATE    REPORTES.FECHADESDE%TYPE            := DSTARTDATE;
V_DENDDATE      REPORTES.FECHAHASTA%TYPE            := DENDDATE;
V_NAFILIADOID   REPORTES.AFILIADOID%TYPE            := NAFILIADOID;
BEGIN
    /* SI TODOS LOS PARAMETROS SON NULL, SE GENERA ERROR */
    IF NVL(V_SCODE,0) = 0 AND NVL(V_NTYPEREPORT,0) = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Parámetros inválidos para la generación o recuperación del reporte.');
    END IF;

    /* SI SE PROPORCIONA SCODE, RECUPERAR PARÁMETROS DEL REPORTE YA GENERADO */
    IF NVL(V_SCODE,0) <> 0 THEN
        /* RECUPERAR PARÁMETROS DEL REPORTE YA GENERADO */
        SELECT TIPO,
               FECHADESDE,
               FECHAHASTA,
               AFILIADOID
          INTO CREATERETRIEVEREPORTDATA.V_NTYPEREPORT,
               CREATERETRIEVEREPORTDATA.V_DSTARTDATE,
               CREATERETRIEVEREPORTDATA.V_DENDDATE,
               CREATERETRIEVEREPORTDATA.V_NAFILIADOID
          FROM REPORTES
          WHERE CODIGOIDENTIFICATORIO = TO_CHAR(SCODE)
        ;
    END IF;
    
    /* SI NO SE ENCUENTRA EL REPORTE, GENERAR ERROR */
    IF NVL(V_NTYPEREPORT,0) = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Reporte no encontrado: ' || SCODE );
    END IF;

    /* PARA ESTE PUNTO YA SE TIENEN LOS PARÁMETROS DEL REPORTE A GENERAR */

    /* GENERAR NUEVO CÓDIGO IDENTIFICATORIO Y GUARDAR PARÁMETROS DEL REPORTE */
    SELECT NVL(MAX(CODIGOIDENTIFICATORIO), '0') INTO V_SCODE FROM REPORTES;
        
    V_SCODE := DECIMAL_TO_HEXA(HEXA_TO_DECIMAL(V_SCODE) + 1);
    
    /* COMPLETAMOS CON 0 A LA IZQUIERDA HASTA TENER 8 CARACTERES */

    WHILE LENGTH(V_SCODE) < 8 LOOP
        V_SCODE := '0' || V_SCODE;
    END LOOP;
    
    INSERT INTO REPORTES ( 
        CODIGOIDENTIFICATORIO,
        TIPO,
        FECHADESDE,
        FECHAHASTA,
        AFILIADOID,
        FECHAGENERACION
    ) VALUES (
        V_SCODE,
        V_NTYPEREPORT,
        V_DSTARTDATE,
        V_DENDDATE,
        V_NAFILIADOID,
        TRUNC(SYSDATE)
    );
    COMMIT;

    HEXAID := V_SCODE;
    
    CASE V_NTYPEREPORT
      WHEN 1 THEN  -- Altas de Afiliados
        REPORTE_AFILIADOS(V_DSTARTDATE, V_DENDDATE, REPORTCURSOR);

      WHEN 2 THEN  -- Altas de Prestadores
        REPORTE_PRESTADORES(V_DSTARTDATE, V_DENDDATE, REPORTCURSOR);

      WHEN 3 THEN  -- Prestadores por Especialidad y Código Postal
        REPORTE_ESPECIALIDAD_CP(REPORTCURSOR);

      WHEN 4 THEN  -- Situaciones Terapéuticas por Afiliado
        REPORTE_SITUACIONES(V_NAFILIADOID, REPORTCURSOR);

      WHEN 5 THEN  -- Prestadores sin Agenda
        REPORTE_SIN_AGENDA(REPORTCURSOR);

      ELSE
        RAISE_APPLICATION_ERROR(-20001, 'Tipo de reporte no reconocido: ' || V_NTYPEREPORT);
    END CASE;
END CREATERETRIEVEREPORTDATA;
/*==============================================================*/
/* REPORTE 1 - ALTAS DE AFILIADOS POR PERÍODO                   */
/*==============================================================*/
PROCEDURE REPORTE_AFILIADOS (
    DSTARTDATE      IN DATE,
    DENDDATE        IN DATE,
    REPORTCURSOR    IN OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN REPORTCURSOR FOR
        SELECT AF.ALTA AS FECHAALTA,
               P.NOMBRE || ' ' || P.APELLIDO AS NOMBRECOMPLETO,
               D.NUMERO AS DOCUMENTO,
               PM.NOMBRE AS PLANMEDICO,
               (SELECT TO_CHAR(COUNT(*)) FROM PERSONAS P2 WHERE P2.AFILIADOID = AF.ID) AS INTEGRANTES
          FROM AFILIADOS AF
               INNER JOIN PERSONAS P ON P.AFILIADOID = AF.ID
               INNER JOIN DOCUMENTACIONES D ON D.PERSONAID = P.ID
               INNER JOIN PLANES_MEDICOS PM ON AF.PLANMEDICOID = PM.ID
         WHERE AF.TITULARID = P.ID
               AND TRUNC(AF.ALTA) BETWEEN TRUNC(NVL(DSTARTDATE,AF.ALTA)) AND TRUNC(NVL(DENDDATE,AF.ALTA))
        ;
  END REPORTE_AFILIADOS;

  /*==============================================================*/
  /* REPORTE 2 - ALTAS DE PRESTADORES POR PERÍODO                 */
  /*==============================================================*/
  PROCEDURE REPORTE_PRESTADORES ( 
    DSTARTDATE      IN DATE,
    DENDDATE        IN DATE,
    REPORTCURSOR    IN OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN REPORTCURSOR FOR
        SELECT MAX(P.ALTA) AS FECHAALTA,
               P.NOMBRECOMPLETO AS NOMBRECOMPLETO,
               MIN(D.NUMERO) AS DOCUMENTO,
               LISTAGG(DISTINCT E.NOMBRE, ', ') WITHIN GROUP (ORDER BY E.NOMBRE) AS ESPECIALIDADES
        FROM PRESTADORES P
             INNER JOIN DOCUMENTACIONES D ON D.PRESTADORID = P.ID
             INNER JOIN ESPECIALIZACIONES EP ON EP.PRESTADORID = P.ID
             INNER JOIN ESPECIALIDADES E ON EP.ESPECIALIDADID = E.ID
        WHERE TRUNC(P.ALTA) BETWEEN TRUNC(NVL(DSTARTDATE,P.ALTA)) AND TRUNC(NVL(DENDDATE,P.ALTA))
        GROUP BY P.ID, P.NOMBRECOMPLETO
        ;
  END REPORTE_PRESTADORES;

  /*==============================================================*/
  /* REPORTE 3 - PRESTADORES POR ESPECIALIDAD Y CÓDIGO POSTAL     */
  /*==============================================================*/
  PROCEDURE REPORTE_ESPECIALIDAD_CP (
    REPORTCURSOR    IN OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN REPORTCURSOR FOR
        SELECT DISTINCT P.NOMBRECOMPLETO AS NOMBRECOMPLETO,
               E.NOMBRE AS ESPECIALIDAD,
               DOC.NUMERO AS DOCUMENTO,
               TO_CHAR(DIR.CODIGOPOSTAL) AS CODIGOPOSTAL
        FROM PRESTADORES P
             INNER JOIN DOCUMENTACIONES DOC ON DOC.PRESTADORID = P.ID
             INNER JOIN DIRECCIONES DIR ON DIR.PRESTADORID = P.ID
             INNER JOIN ESPECIALIZACIONES EP ON EP.PRESTADORID = P.ID
             INNER JOIN ESPECIALIDADES E ON EP.ESPECIALIDADID = E.ID
        WHERE P.BAJA IS NULL OR TRUNC(P.BAJA) >= TRUNC(SYSDATE)
        ORDER BY E.NOMBRE
        ;
  END REPORTE_ESPECIALIDAD_CP;

  /*==============================================================*/
  /* REPORTE 4 - SITUACIONES TERAPÉUTICAS POR AFILIADO            */
  /*==============================================================*/
  PROCEDURE REPORTE_SITUACIONES (
    NAFILIADOID     IN NUMBER,
    REPORTCURSOR    IN OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN REPORTCURSOR FOR
        SELECT TO_CHAR(A.NUMEROAFILIADO) AS NUMEROAFILIADO,
               P.NOMBRE || ' ' || P.APELLIDO AS NOMBRECOMPLETO,
               TO_CHAR(P.PARENTESCO) AS PARENTESCO,
               LISTAGG(DISTINCT ST.NOMBRE, ', ') WITHIN GROUP (ORDER BY ST.NOMBRE) AS SITUACIONESTERAPEUTICAS
          FROM AFILIADOS A
               INNER JOIN PERSONAS P ON P.AFILIADOID = A.ID 
               LEFT JOIN HISTORIALESTERAPEUTICOS HT ON HT.PERSONAID = P.ID
               LEFT JOIN SITUACIONES_TERAPEUTICAS ST ON HT.SITUACIONTERAPEUTICAID = ST.ID
         WHERE A.ID = NVL(NAFILIADOID,A.ID)
           AND (A.BAJA IS NULL OR TRUNC(A.BAJA) >= TRUNC(SYSDATE))
           AND (HT.FECHAFIN IS NULL OR TRUNC(HT.FECHAFIN) >= TRUNC(SYSDATE))
         GROUP BY A.NUMEROAFILIADO, P.NOMBRE, P.APELLIDO, P.PARENTESCO, A.TITULARID
         ORDER BY A.TITULARID
        ;
  END REPORTE_SITUACIONES;
  /*==============================================================*/
  /* REPORTE 5 - PRESTADORES SIN AGENDA DE TURNOS                 */
  /*==============================================================*/
  PROCEDURE REPORTE_SIN_AGENDA (
    REPORTCURSOR    IN OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN REPORTCURSOR FOR
        SELECT P.NOMBRECOMPLETO AS NOMBRECOMPLETO,
               D.NUMERO AS DOCUMENTO,
               (SELECT TO_CHAR(COUNT(*)) FROM DIRECCIONES D2 WHERE D2.PRESTADORID = P.ID) AS DIRECCIONES
          FROM PRESTADORES P
               INNER JOIN DOCUMENTACIONES D ON D.PRESTADORID = P.ID 
               LEFT JOIN AGENDAS AG ON AG.PROFESIONALID = P.ID
               LEFT JOIN HORARIOS_ATENCION HA ON HA.AGENDAID = AG.ID
         WHERE HA.ID IS NULL
           AND (P.BAJA IS NULL OR TRUNC(P.BAJA) >= TRUNC(SYSDATE))
           AND P.ROL <> 2
        ;
  END REPORTE_SIN_AGENDA;

END REPORTDATAGENERATOR;