// <auto-generated />
using System;
using Infrastructure.Persistence.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20251130222416_NewAttributeInReportsMigration")]
    partial class NewAttributeInReportsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Afiliado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<int>("NumeroAfiliado")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMEROAFILIADO");

                    b.Property<int>("PlanMedicoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PLANMEDICOID");

                    b.Property<int>("TitularID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TITULARID");

                    b.HasKey("Id")
                        .HasName("PK_AFILIADOS");

                    b.HasIndex("PlanMedicoId")
                        .HasDatabaseName("IX_AFILIADOS_PLANMEDICOID");

                    b.ToTable("AFILIADOS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DIRECCIONID");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)")
                        .HasColumnName("DISCRIMINATOR");

                    b.HasKey("Id")
                        .HasName("PK_AGENDAS");

                    b.HasIndex("DireccionId")
                        .HasDatabaseName("IX_AGENDAS_DIRECCIONID");

                    b.ToTable("AGENDAS", (string)null);

                    b.HasDiscriminator().HasValue("Agenda");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altura")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("ALTURA");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("CALLE");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CODIGOPOSTAL");

                    b.Property<string>("Departamento")
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("DEPARTAMENTO");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAID");

                    b.Property<string>("Piso")
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("PISO");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRESTADORID");

                    b.Property<string>("ProvinciaCiudad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("PROVINCIACIUDAD");

                    b.HasKey("Id")
                        .HasName("PK_DIRECCIONES");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("IX_DIRECCIONES_PERSONAID");

                    b.HasIndex("PrestadorId")
                        .HasDatabaseName("IX_DIRECCIONES_PRESTADORID");

                    b.ToTable("DIRECCIONES", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Documentacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("NUMERO");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAID");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRESTADORID");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPODOCUMENTO");

                    b.HasKey("Id")
                        .HasName("PK_DOCUMENTACIONES");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasDatabaseName("IX_DOCUMENTACIONES_PERSONAID")
                        .HasFilter("\"PERSONAID\" IS NOT NULL");

                    b.HasIndex("PrestadorId")
                        .HasDatabaseName("IX_DOCUMENTACIONES_PRESTADORID");

                    b.ToTable("DOCUMENTACIONES", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("CORREO");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAID");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRESTADORID");

                    b.HasKey("Id")
                        .HasName("PK_EMAILS");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("IX_EMAILS_PERSONAID");

                    b.HasIndex("PrestadorId")
                        .HasDatabaseName("IX_EMAILS_PRESTADORID");

                    b.ToTable("EMAILS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id")
                        .HasName("PK_ESPECIALIDADES");

                    b.ToTable("ESPECIALIDADES", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HorarioAtencion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AGENDAID");

                    b.Property<int>("DuracionConsultaMinutos")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DURACIONCONSULTAMINUTOS");

                    b.Property<int>("EspecialidadId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ESPECIALIDADID");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HORAFIN");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("HORAINICIO");

                    b.Property<int?>("ProfesionalAsignadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFESIONALASIGNADOID");

                    b.HasKey("Id")
                        .HasName("PK_HORARIOS_ATENCION");

                    b.HasIndex("AgendaId")
                        .HasDatabaseName("IX_HORARIOS_ATENCION_AGENDAID");

                    b.HasIndex("EspecialidadId")
                        .HasDatabaseName("IX_HORARIOS_ATENCION_ESPECIALIDADID");

                    b.HasIndex("ProfesionalAsignadoId")
                        .HasDatabaseName("IX_HORARIOS_ATENCION_PROFESIONALASIGNADOID");

                    b.ToTable("HORARIOS_ATENCION", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HorarioDia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Dia")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DIA");

                    b.Property<int>("HorarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("HORARIOID");

                    b.HasKey("Id")
                        .HasName("PK_HORARIODIA");

                    b.HasIndex("HorarioId")
                        .HasDatabaseName("IX_HORARIODIA_HORARIOID");

                    b.ToTable("HORARIODIA");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AfiliadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AFILIADOID");

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("APELLIDO");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHANACIMIENTO");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR2(64)")
                        .HasColumnName("NOMBRE");

                    b.Property<int>("NumeroIntegrante")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMEROINTEGRANTE");

                    b.Property<int>("Parentesco")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PARENTESCO");

                    b.HasKey("Id")
                        .HasName("PK_PERSONAS");

                    b.HasIndex("AfiliadoId")
                        .HasDatabaseName("IX_PERSONAS_AFILIADOID");

                    b.ToTable("PERSONAS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PlanMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<int>("CostoMensual")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("COSTOMENSUAL");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("NVARCHAR2(3)")
                        .HasColumnName("MONEDA");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("NVARCHAR2(32)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id")
                        .HasName("PK_PLANES_MEDICOS");

                    b.ToTable("PLANES_MEDICOS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Prestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("NVARCHAR2(13)")
                        .HasColumnName("DISCRIMINATOR");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("NOMBRECOMPLETO");

                    b.Property<int>("Rol")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ROL");

                    b.HasKey("Id")
                        .HasName("PK_PRESTADORES");

                    b.ToTable("PRESTADORES", (string)null);

                    b.HasDiscriminator().HasValue("Prestador");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.RegistroTerapeutico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHAFIN");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHAINICIO");

                    b.Property<int>("PersonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAID");

                    b.Property<int>("SituacionTerapeuticaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("SITUACIONTERAPEUTICAID");

                    b.HasKey("Id")
                        .HasName("PK_HISTORIALESTERAPEUTICOS");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("IX_HISTORIALESTERAPEUTICOS_PERSONAID");

                    b.HasIndex("SituacionTerapeuticaId")
                        .HasDatabaseName("IX_HISTORIALESTERAPEUTICOS_SITUACIONTERAPEUTICAID");

                    b.ToTable("HISTORIALESTERAPEUTICOS");
                });

            modelBuilder.Entity("Domain.Entities.Reporte", b =>
                {
                    b.Property<string>("CodigoIdentificatorio")
                        .HasMaxLength(8)
                        .HasColumnType("CHAR(8)")
                        .HasColumnName("CODIGOIDENTIFICATORIO")
                        .IsFixedLength();

                    b.Property<int?>("AfiliadoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("AFILIADOID");

                    b.Property<DateTime?>("FechaDesde")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHADESDE");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHAGENERACION");

                    b.Property<DateTime?>("FechaHasta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FECHAHASTA");

                    b.Property<string>("FileURL")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("FILEURL");

                    b.Property<int>("Tipo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TIPO");

                    b.HasKey("CodigoIdentificatorio")
                        .HasName("PK_REPORTES");

                    b.ToTable("REPORTES");
                });

            modelBuilder.Entity("Domain.Entities.SituacionTerapeutica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Alta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ALTA");

                    b.Property<DateTime?>("Baja")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("BAJA");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("NVARCHAR2(512)")
                        .HasColumnName("DESCRIPCION");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("NOMBRE");

                    b.HasKey("Id")
                        .HasName("PK_SITUACIONES_TERAPEUTICAS");

                    b.ToTable("SITUACIONES_TERAPEUTICAS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Telefono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("NUMERO");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PERSONAID");

                    b.Property<int?>("PrestadorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRESTADORID");

                    b.HasKey("Id")
                        .HasName("PK_TELEFONOS");

                    b.HasIndex("PersonaId")
                        .HasDatabaseName("IX_TELEFONOS_PERSONAID");

                    b.HasIndex("PrestadorId")
                        .HasDatabaseName("IX_TELEFONOS_PRESTADORID");

                    b.ToTable("TELEFONOS", (string)null);
                });

            modelBuilder.Entity("ESPECIALIZACIONES", b =>
                {
                    b.Property<int>("ESPECIALIDADID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PRESTADORID")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ESPECIALIDADID", "PRESTADORID");

                    b.HasIndex("PRESTADORID");

                    b.ToTable("ESPECIALIZACIONES");
                });

            modelBuilder.Entity("Domain.Entities.AgendaCentroMedico", b =>
                {
                    b.HasBaseType("Domain.Entities.Agenda");

                    b.Property<int>("CentroMedicoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CENTROMEDICOID");

                    b.HasIndex("CentroMedicoId")
                        .HasDatabaseName("IX_AGENDAS_CENTROMEDICOID");

                    b.ToTable("AGENDAS");

                    b.HasDiscriminator().HasValue("AgendaCentroMedico");
                });

            modelBuilder.Entity("Domain.Entities.AgendaProfesional", b =>
                {
                    b.HasBaseType("Domain.Entities.Agenda");

                    b.Property<int>("ProfesionalId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFESIONALID");

                    b.HasIndex("ProfesionalId")
                        .HasDatabaseName("IX_AGENDAS_PROFESIONALID");

                    b.ToTable("AGENDAS");

                    b.HasDiscriminator().HasValue("AgendaProfesional");
                });

            modelBuilder.Entity("Domain.Entities.CentroMedico", b =>
                {
                    b.HasBaseType("Domain.Entities.Prestador");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RAZONSOCIAL");

                    b.ToTable("PRESTADORES");

                    b.HasDiscriminator().HasValue("CentroMedico");
                });

            modelBuilder.Entity("Domain.Entities.Profesional", b =>
                {
                    b.HasBaseType("Domain.Entities.Prestador");

                    b.Property<int?>("CentroId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CENTROID");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)")
                        .HasColumnName("MATRICULA");

                    b.HasIndex("CentroId")
                        .HasDatabaseName("IX_PRESTADORES_CENTROID");

                    b.ToTable("PRESTADORES");

                    b.HasDiscriminator().HasValue("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.Afiliado", b =>
                {
                    b.HasOne("Domain.Entities.PlanMedico", "PlanMedico")
                        .WithMany("Afiliados")
                        .HasForeignKey("PlanMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AFILIADOS_PLANES_MEDICOS_PLANMEDICOID");

                    b.Navigation("PlanMedico");
                });

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.HasOne("Domain.Entities.Direccion", "DireccionAtencion")
                        .WithMany()
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AGENDAS_DIRECCIONES_DIRECCIONID");

                    b.Navigation("DireccionAtencion");
                });

            modelBuilder.Entity("Domain.Entities.Direccion", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_DIRECCIONES_PERSONAS_PERSONAID");

                    b.HasOne("Domain.Entities.Prestador", "Prestador")
                        .WithMany("Direcciones")
                        .HasForeignKey("PrestadorId")
                        .HasConstraintName("FK_DIRECCIONES_PRESTADORES_PRESTADORID");

                    b.Navigation("Persona");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Domain.Entities.Documentacion", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithOne("Documentacion")
                        .HasForeignKey("Domain.Entities.Documentacion", "PersonaId")
                        .HasConstraintName("FK_DOCUMENTACIONES_PERSONAS_PERSONAID");

                    b.HasOne("Domain.Entities.Prestador", "Prestador")
                        .WithMany("Documentacion")
                        .HasForeignKey("PrestadorId")
                        .HasConstraintName("FK_DOCUMENTACIONES_PRESTADORES_PRESTADORID");

                    b.Navigation("Persona");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Domain.Entities.Email", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("Emails")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_EMAILS_PERSONAS_PERSONAID");

                    b.HasOne("Domain.Entities.Prestador", "Prestador")
                        .WithMany("Emails")
                        .HasForeignKey("PrestadorId")
                        .HasConstraintName("FK_EMAILS_PRESTADORES_PRESTADORID");

                    b.Navigation("Persona");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Domain.Entities.HorarioAtencion", b =>
                {
                    b.HasOne("Domain.Entities.Agenda", "Agenda")
                        .WithMany("Horarios")
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HORARIOS_ATENCION_AGENDAS_AGENDAID");

                    b.HasOne("Domain.Entities.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HORARIOS_ATENCION_ESPECIALIDADES_ESPECIALIDADID");

                    b.HasOne("Domain.Entities.Profesional", "ProfesionalAsignado")
                        .WithMany()
                        .HasForeignKey("ProfesionalAsignadoId")
                        .HasConstraintName("FK_HORARIOS_ATENCION_PRESTADORES_PROFESIONALASIGNADOID");

                    b.Navigation("Agenda");

                    b.Navigation("Especialidad");

                    b.Navigation("ProfesionalAsignado");
                });

            modelBuilder.Entity("Domain.Entities.HorarioDia", b =>
                {
                    b.HasOne("Domain.Entities.HorarioAtencion", "Horario")
                        .WithMany("DiasAtencion")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HORARIODIA_HORARIOS_ATENCION_HORARIOID");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.HasOne("Domain.Entities.Afiliado", "Afiliado")
                        .WithMany("Integrantes")
                        .HasForeignKey("AfiliadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PERSONAS_AFILIADOS_AFILIADOID");

                    b.Navigation("Afiliado");
                });

            modelBuilder.Entity("Domain.Entities.RegistroTerapeutico", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("SituacionesTerapeuticas")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HISTORIALESTERAPEUTICOS_PERSONAS_PERSONAID");

                    b.HasOne("Domain.Entities.SituacionTerapeutica", "SituacionTerapeutica")
                        .WithMany()
                        .HasForeignKey("SituacionTerapeuticaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HISTORIALESTERAPEUTICOS_SITUACIONES_TERAPEUTICAS_SITUACIONTERAPEUTICAID");

                    b.Navigation("Persona");

                    b.Navigation("SituacionTerapeutica");
                });

            modelBuilder.Entity("Domain.Entities.Telefono", b =>
                {
                    b.HasOne("Domain.Entities.Persona", "Persona")
                        .WithMany("Telefonos")
                        .HasForeignKey("PersonaId")
                        .HasConstraintName("FK_TELEFONOS_PERSONAS_PERSONAID");

                    b.HasOne("Domain.Entities.Prestador", "Prestador")
                        .WithMany("Telefonos")
                        .HasForeignKey("PrestadorId")
                        .HasConstraintName("FK_TELEFONOS_PRESTADORES_PRESTADORID");

                    b.Navigation("Persona");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("ESPECIALIZACIONES", b =>
                {
                    b.HasOne("Domain.Entities.Especialidad", null)
                        .WithMany()
                        .HasForeignKey("ESPECIALIDADID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Prestador", null)
                        .WithMany()
                        .HasForeignKey("PRESTADORID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.AgendaCentroMedico", b =>
                {
                    b.HasOne("Domain.Entities.CentroMedico", "CentroMedico")
                        .WithMany("Agendas")
                        .HasForeignKey("CentroMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AGENDAS_PRESTADORES_CENTROMEDICOID");

                    b.Navigation("CentroMedico");
                });

            modelBuilder.Entity("Domain.Entities.AgendaProfesional", b =>
                {
                    b.HasOne("Domain.Entities.Profesional", "Profesional")
                        .WithMany("Agendas")
                        .HasForeignKey("ProfesionalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AGENDAS_PRESTADORES_PROFESIONALID");

                    b.Navigation("Profesional");
                });

            modelBuilder.Entity("Domain.Entities.Profesional", b =>
                {
                    b.HasOne("Domain.Entities.CentroMedico", "Centro")
                        .WithMany("Profesionales")
                        .HasForeignKey("CentroId")
                        .HasConstraintName("FK_PRESTADORES_PRESTADORES_CENTROID");

                    b.Navigation("Centro");
                });

            modelBuilder.Entity("Domain.Entities.Afiliado", b =>
                {
                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("Domain.Entities.Agenda", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("Domain.Entities.HorarioAtencion", b =>
                {
                    b.Navigation("DiasAtencion");
                });

            modelBuilder.Entity("Domain.Entities.Persona", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Documentacion")
                        .IsRequired();

                    b.Navigation("Emails");

                    b.Navigation("SituacionesTerapeuticas");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("Domain.Entities.PlanMedico", b =>
                {
                    b.Navigation("Afiliados");
                });

            modelBuilder.Entity("Domain.Entities.Prestador", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("Documentacion");

                    b.Navigation("Emails");

                    b.Navigation("Telefonos");
                });

            modelBuilder.Entity("Domain.Entities.CentroMedico", b =>
                {
                    b.Navigation("Agendas");

                    b.Navigation("Profesionales");
                });

            modelBuilder.Entity("Domain.Entities.Profesional", b =>
                {
                    b.Navigation("Agendas");
                });
#pragma warning restore 612, 618
        }
    }
}
